### ISSUE TITLE
Wrong pyproject.toml is generated for local packages

### ISSUE THREAD

**Issue by frostming** [sarugaku/requirementslib#262]
```python
from requirementslib import Requirement

Requirement.from_pipfile('mypackage', {"path": "./mypackage", "editable": True})
```
This creates a `pyproject.toml` under project root:
```toml
[build-system]
requires = []
build-backend = "setuptools.build_meta:__legacy__"
```
The `setuptools` is missing from `requires`, which causes failure in subsequent installations.
